export interface ProjectFile {
  path: string
  content: string
}

export function generateProjectFiles(contractCode: string, projectName: string = 'contract'): ProjectFile[] {
  const files: ProjectFile[] = []

  // Cargo.toml
  files.push({
    path: 'Cargo.toml',
    content: generateCargoToml(projectName)
  })

  // src/lib.rs
  files.push({
    path: 'src/lib.rs',
    content: contractCode
  })

  // meta/Cargo.toml
  files.push({
    path: 'meta/Cargo.toml',
    content: generateMetaCargoToml(projectName)
  })

  // meta/src/main.rs
  files.push({
    path: 'meta/src/main.rs',
    content: generateMetaMain()
  })

  // README.md
  files.push({
    path: 'README.md',
    content: generateReadme(projectName)
  })

  // .gitignore
  files.push({
    path: '.gitignore',
    content: generateGitignore()
  })

  return files
}

function generateCargoToml(projectName: string): string {
  return `[package]
name = "${projectName}"
version = "0.1.0"
authors = ["AI Contract Generator"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.64.0"

[dev-dependencies.multiversx-sc-scenario]
version = "0.64.0"

[dev-dependencies.multiversx-sc-meta]
version = "0.64.0"
`
}

function generateMetaCargoToml(projectName: string): string {
  return `[package]
name = "${projectName}-meta"
version = "0.1.0"
authors = ["AI Contract Generator"]
edition = "2021"
publish = false

[dependencies.multiversx-sc-meta]
version = "0.64.0"

[dependencies.${projectName}]
path = ".."
`
}

function generateMetaMain(): string {
  return `fn main() {
    multiversx_sc_meta::cli_main::<contract::AbiProvider>();
}
`
}

function generateReadme(projectName: string): string {
  return `# ${projectName}

AI-generated MultiversX smart contract.

## Build

\`\`\`bash
mxpy contract build
\`\`\`

## Test

\`\`\`bash
mxpy contract test
\`\`\`

## Deploy

\`\`\`bash
mxpy contract deploy --pem=wallet.pem --recall-nonce --gas-limit=60000000
\`\`\`

---

Generated by AI Contract Generator
`
}

function generateGitignore(): string {
  return `# Rust
target/
output/
*.wasm
*.abi.json

# IDE
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db

# Deployment
wallet.pem
*.pem
`
}
