// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        init => init
        upgrade => upgrade
        setTemplateNftTokenId => set_template_nft_token_id
        generateContract => generate_contract
        completeGeneration => complete_generation
        mintTemplateNFT => mint_template_nft
        listTemplate => list_template
        purchaseTemplate => purchase_template
        cancelListing => cancel_listing
        rateTemplate => rate_template
        setDailyLimit => set_daily_limit
        setMintingFee => set_minting_fee
        withdrawFees => withdraw_fees
        getGeneration => get_generation
        getListing => get_listing
        getUserGenerationsToday => get_user_generations_today
        getUserGenerationCount => get_user_generation_count
        getTemplateRating => get_template_rating
        getTemplateUses => get_template_uses
        getDailyLimit => get_daily_limit
        getMintingFee => get_minting_fee
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
